import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
const cap=(...args)=>execFileSync(process.execPath,['node_modules/@capacitor/cli/bin/capacitor',...args],{stdio:'inherit'});
if(!existsSync('android'))cap('add','android');
cap('sync','android');
await import('./generate-icons.mjs');
const gradle='android/app/build.gradle';
const version=JSON.parse(readFileSync('package.json','utf8')).version;
const run=Number(process.env.GITHUB_RUN_NUMBER||1);
writeFileSync(gradle,readFileSync(gradle,'utf8').replace(/versionName "[^"]+"/,`versionName "${version}"`).replace(/versionCode \d+/,`versionCode ${run}`));
const styles='android/app/src/main/res/values/styles.xml';
writeFileSync(styles,readFileSync(styles,'utf8').replace('<item name="android:background">@drawable/splash</item>','<item name="windowSplashScreenBackground">#154e43</item><item name="windowSplashScreenAnimatedIcon">@drawable/ic_launcher_foreground</item><item name="postSplashScreenTheme">@style/AppTheme.NoActionBar</item>'));
